### ISSUE TITLE
Multi-column Assign

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-expr#355]
Maybe it's time to have assign handle multiple columns at once

```
    Projection: columns=['sum_disc_price', 'avg_qty', 'count_order', 'sum_charge', 'avg_disc', 'l_linestatus', 'l_returnflag', 'sum_qty', 'sum_base_price', 'avg_price']
      Assign: key='count_order'
        Projection: columns=['avg_disc', 'avg_price', 'avg_qty', 'l_linestatus', 'l_returnflag', 'sum_base_price', 'sum_charge', 'sum_disc_price', 'sum_qty']
          Assign: key='avg_disc'
            Projection: columns=['avg_price', 'avg_qty', 'l_linestatus', 'l_returnflag', 'sum_base_price', 'sum_charge', 'sum_disc_price', 'sum_qty']
              Assign: key='sum_charge'
                Projection: columns=['avg_price', 'avg_qty', 'l_linestatus', 'l_returnflag', 'sum_base_price', 'sum_disc_price', 'sum_qty']
                  Assign: key='sum_disc_price'
                    Projection: columns=['avg_price', 'avg_qty', 'l_linestatus', 'l_returnflag', 'sum_base_price', 'sum_qty']
                      Assign: key='avg_price'
                        Projection: columns=['avg_qty', 'l_linestatus', 'l_returnflag', 'sum_base_price', 'sum_qty']
                          Assign: key='avg_qty'
                            Projection: columns=['l_linestatus', 'l_returnflag', 'sum_base_price', 'sum_qty']
                              Assign: key='sum_base_price'
                                Assign: key='sum_qty'
                                  Projection: columns=['l_linestatus', 'l_returnflag']
                                    Filter:
                                      ReadParquet: path='s3://coiled-runtime-ci/tpch/scale-100/lineitem' columns=['l_discount', 'l_extendedprice', 'l_linestatus', 'l_orderkey', 'l_quantity', 'l_returnflag', 'l_shipdate', 'l_tax'] kwargs={'dtype_backend': 'pyarrow'}

```
